Code Refactored
datakaveri/iudx-gis-interface pull request #40
Opened 2022-04-11 08:39 UTC by gopal-mahajan

PR includes :
- changes in status code and response
- Readme and Setup  file updated 
- Code Refactored

2022-04-11 08:44 UTC, karun-singh commented on Jenkinsfile
> +          return env.GIT_BRANCH == 'origin/v3.5.0';
```suggestion
          return env.GIT_BRANCH == 'origin/master';
```
This needs to reflect the correct branch which would be master in this case.

2022-04-11 12:06 UTC, kailash commented
ok to test

2022-04-11 13:10 UTC, karun-singh commented
@gopal-mahajan Need to update the collection name in the Jenkinsfile here as well.

2022-04-11 13:48 UTC, karun-singh requested changes

2022-04-11 13:48 UTC, karun-singh commented on Jenkinsfile
> +            sh 'scp src/test/resources/IUDX_GIS_Server_APIs(v3.5.0).postman_collection.json jenkins@jenkins-master:/var/lib/jenkins/iudx/gis/Newman/'
```suggestion
            sh 'scp src/test/resources/IUDX_GIS_Server_APIs\(v3.5.0\).postman_collection.json jenkins@jenkins-master:/var/lib/jenkins/iudx/gis/Newman/'
```
need to escape the parentheses

2022-04-11 13:48 UTC, karun-singh commented on Jenkinsfile
> +            sh 'HTTP_PROXY=\'127.0.0.1:8090\' newman run /var/lib/jenkins/iudx/gis/Newman/IUDX_GIS_Server_APIs(v3.5.0).postman_collection.json -e /home/ubuntu/configs/gis-postman-env.json --insecure
```suggestion
            sh 'HTTP_PROXY=\'127.0.0.1:8090\' newman run /var/lib/jenkins/iudx/gis/Newman/IUDX_GIS_Server_APIs\(v3.5.0\).postman_collection.json -e /home/ubuntu/configs/gis-postman-env.json --insecure -r htmlextra --reporter-htmlextra-export /var/lib/jenkins/iudx/gis/Newman/report/report.html --reporter-htmlextra-skipSensitiveData'
```
need to escape the parentheses

2022-04-11 14:34 UTC, karun-singh approved these changes

2022-04-12 05:13 UTC, kailash commented
retest this please

2022-04-12 05:17 UTC, kailash approved these changes

2022-04-12 05:17 UTC, merged