Setupdocs
datakaveri/iudx-gis-interface pull request #90
Opened 2023-03-20 12:42 UTC by ankitmashu

2023-03-20 14:51 UTC, kailash commented
ok to test

2023-03-21 03:38 UTC, kailash requested changes
Check preview of your document [here](https://github.com/ankitmashu/iudx-gis-interface/blob/setupdocs/SETUP.md), 

1. duplicate `setting up RMQ` heading
2. incorrectly formatted Databroker Verticle config

2023-03-21 03:46 UTC, ankitmashu commented
> Check preview of your document [here](https://github.com/ankitmashu/iudx-gis-interface/blob/setupdocs/SETUP.md),
> 
> 1. duplicate `setting up RMQ` heading
> 2. incorrectly formatted Databroker Verticle config

Solved issue

2023-03-21 03:48 UTC, kailash commented on SETUP.md
> +- In Metering Verticle we are pushing data in Auditing Verticle through RabbitMQ. [config-example.json](configs/config-example.json).
```suggestion
- In Metering Verticle we are pushing data in Auditing server through RabbitMQ. [config-example.json](configs/config-example.json).
```

2023-03-21 04:21 UTC, merged